<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.2.1" />
    <PackageReference Include="System.IO.Ports" Version="10.0.0" />
    <ProjectReference Include="..\TajpanShowController.Core\TajpanShowController.Core.csproj" />
  </ItemGroup>
</Project>
